pipeline {
    agent any


    stages {
        
        stage('Клонирование репозитория') {
            steps {
                git branch: 'main', url: 'https://github.com/LevShlyogin/Automating_machine_learning.git'
            }
        }
        
        stage('Установка библиотек и зависимостей') {
            steps {
                sh 'pip install -r "Module 2/model/requirements.txt"'
            }
        }

        
        stage('Запуск Python-скрипта для подготовки данных') {
            steps {
                sh 'python3 "Module 2/model/data_creation.py"'
            }
        }

        stage('Создание модели машинного обучения') {
            steps {
                sh 'python3 "Module 2/model/model_preprocessing.py"'
            }
        }
        
        stage('Обучение модели машинного обучения') {
            steps {
                sh 'python3 "Module 2/model//model_preparation.py"'
            }
        }

        stage('Проверка модели машинного обучения') {
            steps {
                sh 'python3 "Module 2/model/model_testing.py"'
            }
        }
    }
}
